apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: myapp
    key: value
spec:
  containers:
  - name: myappcontainer
    image: nginx
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: mypod1
  labels:
    app: myapp
    key: value
spec:
  containers:
  - name: myappcontainer1
    image: nginx
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: mypod2
  labels:
    app: myapp
    key: value
spec:
  containers:
  - name: myappcontainer2
    image: nginx
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: mypod3
  labels:
    app: myapp
    key: value
spec:
  containers:
  - name: myappcontainer3
    image: nginx
    ports:
    - containerPort: 80
